server:
  servlet.context-path: /${spring.application.name}
  port: 8443
  non-secure-port: 8080
  ssl:
    client-auth: WANT
    trust-store: 'classpath:/testCA.p12'
    trust-store-type: PKCS12
    trust-store-password: 'ChangeIt'
    key-store: 'classpath:/testServer.p12'
    key-store-type: PKCS12
    key-store-password: 'ChangeIt'
  outbound-ssl:
    trust-store: ${server.ssl.trust-store}
    trust-store-type: ${server.ssl.trust-store-type}
    trust-store-password: ${server.ssl.trust-store-password}
    key-store: ${server.ssl.key-store}
    key-store-type: ${server.ssl.key-store-type}
    key-store-password: ${server.ssl.key-store-password}

management:
  endpoints.web.base-path: "/mgmt"
  endpoints.web.exposure.include: "*"
  endpoint.health.show-details: when-authorized

spring:
  security:
    user.password: passwordNotUsed
    datawave:
      jwt.ttl: 86400
      issuers-required: true
      enforce-allowed-callers: false
      manager-roles: Administrator,JBossAdministrator
  # Enable service discovery using Consul
  cloud:
    discovery:
      enabled: true
    consul:
      enabled: true
      host: discovery
      discovery:
        port: ${server.non-secure-port}
        health-check-path: ${server.servlet.context-path}${management.endpoints.web.base-path}/health
        health-check-interval: 15s
        instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
      # Allow a long time for the Consul agent to become available.
      retry:
        max-attempts: 120
  # Use discovery to find the RabbitMQ server
  rabbitmq:
    discovery:
      enabled: true
      failFast: true
